"""DeepSeek-backed Q10 row analysis for financial MAS construction."""
from __future__ import annotations

import hashlib
import json
import logging
import re
from typing import Any

from .financial_profiles import get_financial_profile


TASK_ID = re.compile(r"^[a-z][a-z0-9_]{1,63}$")
ALLOWED_RELATIONS = {"precedes", "requires", "reviews", "feedback"}
ALLOWED_RISK_LEVELS = {"low", "medium", "high"}
ALLOWED_EVIDENCE_MODES = {"filing", "table", "mixed"}
LOGGER = logging.getLogger(__name__)
REQUIRED_FIELDS = {"task_family", "risk_level", "evidence_mode", "tasks", "edges", "constraints"}


def analyze_financial_row(dataset: str, row: dict[str, Any], llm=None, seed: int = 11) -> dict[str, Any]:
    profile = get_financial_profile(dataset)
    prompt = _prompt(profile, row)
    LOGGER.warning("Q10 analyze_financial_row llm_is_none=%s dataset=%s seed=%s", llm is None, dataset, seed)
    if llm is None:
        raise ValueError("Q10 row analysis requires a DeepSeek-backed LLM adapter; llm=None is not allowed")

    response = llm.generate_json(
        "You are a financial MAS architecture analyst. Analyze task structure only, not the gold answer. Return valid JSON.",
        prompt,
        seed,
        REQUIRED_FIELDS,
    )
    LOGGER.warning(
        "Q10 analyze_financial_row provider=%s model=%s dataset=%s seed=%s",
        response.provider,
        response.model,
        dataset,
        seed,
    )
    if str(response.provider).casefold() == "deterministic" or str(response.model).casefold().startswith("deterministic"):
        raise ValueError("Q10 row analysis must be generated by DeepSeek, not the deterministic offline adapter")

    analysis = _normalize_llm_analysis(profile, response.value)
    _sanitize(profile, analysis)
    analysis["analysis_source"] = response.provider
    analysis["model"] = response.model
    analysis["model_calls"] = 1
    analysis["raw_response_sha256"] = hashlib.sha256(response.raw_text.encode("utf-8")).hexdigest()
    return analysis


def _prompt(profile: dict[str, Any], row: dict[str, Any]) -> str:
    payload = {
        "dataset": profile["dataset"],
        "dataset_profile": profile,
        "question": row.get("question", ""),
        "context": row.get("context", ""),
        "choices": row.get("choices", []),
        "instruction": "Infer the required financial application task graph. Do not return or infer the gold answer. Keep tasks abstract and implementation-independent.",
        "required_json_shape": {
            "task_family": "string",
            "financial_focus": "string",
            "risk_level": "low|medium|high",
            "evidence_mode": "filing|table|mixed",
            "tasks": [{"id": "snake_case_task", "objective": "abstract objective"}],
            "edges": [{"source": "task_id", "target": "task_id", "relation": "precedes|requires|reviews|feedback"}],
            "constraints": [{"id": "constraint_id", "target": "task_id", "predicate": "required"}],
        },
    }
    return json.dumps(payload, ensure_ascii=False)


def _normalize_llm_analysis(profile: dict[str, Any], raw: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raise ValueError("Q10 analysis must be a JSON object")
    analysis = dict(raw)
    analysis["dataset"] = profile["dataset"]
    analysis["profile"] = profile
    if not isinstance(analysis.get("financial_focus"), str) or not str(analysis.get("financial_focus", "")).strip():
        analysis["financial_focus"] = "dataset-driven financial application construction"
    return analysis


def _sanitize(profile: dict[str, Any], analysis: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(analysis, dict):
        raise ValueError("Q10 analysis must be a JSON object")
    _require_string(analysis, "task_family")
    _require_string(analysis, "financial_focus")
    _require_string(analysis, "risk_level")
    _require_string(analysis, "evidence_mode")

    risk_level = analysis["risk_level"]
    if risk_level not in ALLOWED_RISK_LEVELS:
        raise ValueError(f"invalid risk_level {risk_level!r}; expected one of {sorted(ALLOWED_RISK_LEVELS)}")
    evidence_mode = analysis["evidence_mode"]
    if evidence_mode not in ALLOWED_EVIDENCE_MODES:
        raise ValueError(f"invalid evidence_mode {evidence_mode!r}; expected one of {sorted(ALLOWED_EVIDENCE_MODES)}")

    tasks = analysis.get("tasks")
    if not isinstance(tasks, list):
        raise ValueError("Q10 analysis tasks must be an array")
    if not tasks:
        raise ValueError("Q10 analysis must include at least one task")
    seen_tasks: set[str] = set()
    for index, item in enumerate(tasks):
        if not isinstance(item, dict):
            raise ValueError(f"task[{index}] must be an object")
        task_id = _require_str_field(item, "id", f"task[{index}]")
        objective = _require_str_field(item, "objective", f"task[{index}]")
        if task_id != task_id.strip():
            raise ValueError(f"task[{index}].id may not contain leading or trailing whitespace")
        if objective != objective.strip():
            raise ValueError(f"task[{index}].objective may not contain leading or trailing whitespace")
        if not TASK_ID.match(task_id):
            raise ValueError(f"invalid task id {task_id!r}")
        if task_id in seen_tasks:
            raise ValueError(f"duplicate task id {task_id!r}")
        seen_tasks.add(task_id)

    edges = analysis.get("edges")
    if not isinstance(edges, list):
        raise ValueError("Q10 analysis edges must be an array")
    seen_edges: set[tuple[str, str, str]] = set()
    for index, item in enumerate(edges):
        if not isinstance(item, dict):
            raise ValueError(f"edge[{index}] must be an object")
        source = _require_str_field(item, "source", f"edge[{index}]")
        target = _require_str_field(item, "target", f"edge[{index}]")
        relation = _require_str_field(item, "relation", f"edge[{index}]")
        if source != source.strip():
            raise ValueError(f"edge[{index}].source may not contain leading or trailing whitespace")
        if target != target.strip():
            raise ValueError(f"edge[{index}].target may not contain leading or trailing whitespace")
        if relation != relation.strip():
            raise ValueError(f"edge[{index}].relation may not contain leading or trailing whitespace")
        if source not in seen_tasks:
            raise ValueError(f"edge[{index}] source not found in tasks: {source!r}")
        if target not in seen_tasks:
            raise ValueError(f"edge[{index}] target not found in tasks: {target!r}")
        if source == target:
            raise ValueError(f"edge[{index}] may not be a self-loop: {source!r}")
        if relation not in ALLOWED_RELATIONS:
            raise ValueError(f"invalid edge relation {relation!r}; expected one of {sorted(ALLOWED_RELATIONS)}")
        edge_key = (source, target, relation)
        if edge_key in seen_edges:
            raise ValueError(f"duplicate edge {source!r} -> {target!r} ({relation!r})")
        seen_edges.add(edge_key)

    constraints = analysis.get("constraints")
    if not isinstance(constraints, list):
        raise ValueError("Q10 analysis constraints must be an array")
    seen_constraints: set[str] = set()
    for index, item in enumerate(constraints):
        if not isinstance(item, dict):
            raise ValueError(f"constraint[{index}] must be an object")
        constraint_id = _require_str_field(item, "id", f"constraint[{index}]")
        target = _require_str_field(item, "target", f"constraint[{index}]")
        predicate = _require_str_field(item, "predicate", f"constraint[{index}]")
        if constraint_id != constraint_id.strip():
            raise ValueError(f"constraint[{index}].id may not contain leading or trailing whitespace")
        if target != target.strip():
            raise ValueError(f"constraint[{index}].target may not contain leading or trailing whitespace")
        if predicate != predicate.strip():
            raise ValueError(f"constraint[{index}].predicate may not contain leading or trailing whitespace")
        if not TASK_ID.match(constraint_id):
            raise ValueError(f"invalid constraint id {constraint_id!r}")
        if target not in seen_tasks:
            raise ValueError(f"constraint[{index}] target not found in tasks: {target!r}")
        if not predicate:
            raise ValueError(f"constraint[{index}].predicate must be non-empty")
        if constraint_id in seen_constraints:
            raise ValueError(f"duplicate constraint id {constraint_id!r}")
        seen_constraints.add(constraint_id)

    return analysis


def _require_string(mapping: dict[str, Any], key: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"Q10 analysis field {key!r} must be a non-empty string")
    return value


def _require_str_field(mapping: dict[str, Any], key: str, label: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{label}.{key} must be a non-empty string")
    return value


def _deterministic_analysis(profile: dict[str, Any], row: dict[str, Any]) -> dict[str, Any]:
    stages = profile["baseline_tasks"]
    objectives = {
        "filing_evidence": "Retrieve audited filing evidence and metric definitions",
        "market_risk_evidence": "Retrieve risk-factor, uncertainty and forward-looking evidence",
        "financial_analysis": "Analyze financial metrics, trend drivers and evidence consistency",
        "report_table_evidence": "Retrieve table cells and line items from the financial report",
        "narrative_disclosure_evidence": "Retrieve relevant narrative disclosures and footnotes",
        "calculation_analysis": "Compute the numeric financial result with unit handling",
        "risk_assessment": "Assess material risk, sensitivity and unsupported inference risk",
        "compliance_review": "Check regulatory, disclosure and non-advice constraints",
        "audit_trail": "Record evidence lineage, assumptions and control decisions",
        "final_report": "Return the dataset-specific financial answer contract",
    }
    if profile["dataset"] == "FinanceBench":
        edges = [
            {"source": "filing_evidence", "target": "financial_analysis", "relation": "precedes"},
            {"source": "market_risk_evidence", "target": "risk_assessment", "relation": "precedes"},
            {"source": "financial_analysis", "target": "risk_assessment", "relation": "requires"},
            {"source": "financial_analysis", "target": "compliance_review", "relation": "requires"},
            {"source": "risk_assessment", "target": "audit_trail", "relation": "reviews"},
            {"source": "compliance_review", "target": "audit_trail", "relation": "reviews"},
            {"source": "audit_trail", "target": "final_report", "relation": "precedes"},
            {"source": "compliance_review", "target": "risk_assessment", "relation": "feedback"},
        ]
    else:
        edges = [
            {"source": "report_table_evidence", "target": "calculation_analysis", "relation": "precedes"},
            {"source": "narrative_disclosure_evidence", "target": "risk_assessment", "relation": "precedes"},
            {"source": "calculation_analysis", "target": "risk_assessment", "relation": "requires"},
            {"source": "calculation_analysis", "target": "compliance_review", "relation": "requires"},
            {"source": "risk_assessment", "target": "audit_trail", "relation": "reviews"},
            {"source": "compliance_review", "target": "audit_trail", "relation": "reviews"},
            {"source": "audit_trail", "target": "final_report", "relation": "precedes"},
            {"source": "compliance_review", "target": "calculation_analysis", "relation": "feedback"},
        ]
    return {
        "task_family": profile["task_family"],
        "financial_focus": "dataset-driven financial analysis, risk assessment and compliance review",
        "risk_level": "high",
        "evidence_mode": "table" if profile["dataset"] == "FinQA" else "filing",
        "tasks": [{"id": task, "objective": objectives[task]} for task in stages],
        "edges": edges,
        "constraints": [{"id": control, "target": "final_report", "predicate": "required"} for control in profile["required_controls"]],
    }


def _ensure_path(edges: list[dict[str, str]], source: str, target: str, relation: str = "precedes") -> None:
    if not any(edge["source"] == source and edge["target"] == target for edge in edges):
        edges.append({"source": source, "target": target, "relation": relation})
